version: '3.7'

networks:
  pcs:

services:
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile.test.unit.Dockerfile
    environment:
      - SMS_SERVER=http://smd:27779
      - VAULT_ENABLED=true
      - VAULT_KEYPATH=hms-creds
    depends_on:
      - etcd
      - smd
    networks:
      - pcs
  dummy:
    image: docker.io/alpine:3.13
    depends_on:
      - etcd
      - smd
      - cray-hms-hmcollector
      - emulator-loader
      - vault-kv-enabler
    networks:
      - pcs
  etcd:
    image: quay.io/coreos/etcd:v3.5.17
    environment:
      - ETCD_UNSUPPORTED_ARCH=arm64
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    networks:
      - pcs
  vault:
    hostname: vault
    image: docker.io/library/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - pcs
  vault-kv-enabler:
    build:
      context: .
      dockerfile: vault-kv-enabler.dockerfile
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - KV_STORES=hms-creds
    depends_on:
      - vault
    networks:
      - pcs
  postgres:
    hostname: postgres
    image: docker.io/library/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=hmsds
    networks:
      - pcs
  smd-init:
    image: ghcr.io/openchami/smd:2.17
    environment:
      - SMD_DBHOST=postgres
      - SMD_DBPORT=5432
      - SMD_DBNAME=hmsds
      - SMD_DBUSER=${POSTGRES_USER} # Set in .env file
      - SMD_DBPASS=${POSTGRES_PASSWORD} # Set in .env file
      - SMD_DBOPTS=sslmode=disable
    depends_on:
      - postgres
    networks:
      - pcs
    command: /smd-init
  smd:
    image: ghcr.io/openchami/smd:2.17
    environment:
      -
      - RF_MSG_HOST=kafka:9092:cray-dmtf-resource-event
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - SMD_WVAULT=true
      - SMD_RVAULT=true
      - SMD_SLS_HOST=
      - SMD_HBTD_HOST=
    volumes:
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    hostname: smd
    depends_on:
      - smd-init
      - vault
    ports:
      - "27779:27779"
    networks:
      - pcs
  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pcs
  kafka:
    image: docker.io/confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - pcs
  cray-hms-hmcollector:
    image: hms-hmcollector
    environment:
      - LOG_LEVEL=TRACE
      - SM_URL=http://smd:27779
      - POLLING_ENABLED=false
      - RF_SUBSCRIBE_ENABLED=false
      - REST_PORT=80
      - VAULT_TOKEN=hms
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - VAULT_ADDR=http://vault:8200
      - KAFKA_BROKERS_CONFIG=configs/kafka_brokers_local.json
    volumes:
      - ./configs/kafka_brokers_local.json:/configs/kafka_brokers_local.json
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    networks:
      - pcs

  #
  # Emulator
  #
  emulator-loader:
    image: docker.io/library/golang:1.23-alpine
    command: >
      sh -c "apk add curl && sleep 10 &&
      curl -X POST -d '{\"RedfishEndpoints\":[{
        \"ID\":\"x0c0b0\",
        \"FQDN\":\"x0c0b0\",
        \"RediscoverOnUpdate\":true,
        \"User\":\"root\",
        \"Password\":\"root_password\"
      },{
        \"ID\":\"x0c0s1b0\",
        \"FQDN\":\"x0c0s1b0\",
        \"RediscoverOnUpdate\":true,
        \"User\":\"root\",
        \"Password\":\"root_password\"
      },{
        \"ID\":\"x0c0s2b0\",
        \"FQDN\":\"x0c0s2b0\",
        \"RediscoverOnUpdate\":true,
        \"User\":\"root\",
        \"Password\":\"root_password\"
      },{
        \"ID\":\"x0c0r2b0\",
        \"FQDN\":\"x0c0r2b0\",
        \"RediscoverOnUpdate\":true,
        \"User\":\"root\",
        \"Password\":\"root_password\"}]}' http://smd:27779/hsm/v2/Inventory/RedfishEndpoints"
    depends_on:
      - smd
      - rfemulator0
      - rfemulator1
      - rfemulator2
      - rfemulator3
    networks:
      - pcs

  rfemulator0:
    hostname: x0c0b0
    image: ghcr.io/openchami/csm-rie:v1.6.7
    environment:
      - MOCKUPFOLDER=CMM
      - XNAME=x0c0b0
      # - "AUTH_CONFIG=root:root_password:Administrator"
      - PORT=443
    ports:
      - "5004:443"
    networks:
      pcs:
        aliases:
          - x0c0b0

  rfemulator1:
    hostname: x0c0s1b0
    image: ghcr.io/openchami/csm-rie:v1.6.7
    environment:
      - MOCKUPFOLDER=EX235a
      - MAC_SCHEMA=Mountain
      - XNAME=x0c0s1b0
      # - "AUTH_CONFIG=root:root_password:Administrator"
      - PORT=443
    ports:
      - "5001:443"
    networks:
      pcs:
        aliases:
          - x0c0s1b0

  rfemulator2:
    hostname: x0c0s2b0
    image: ghcr.io/openchami/csm-rie:v1.6.7
    environment:
      - MOCKUPFOLDER=EX235a
      - MAC_SCHEMA=Mountain
      - XNAME=x0c0s2b0
      # - "AUTH_CONFIG=root:root_password:Administrator"
      - PORT=443
    ports:
      - "5002:443"
    networks:
      pcs:
        aliases:
          - x0c0s2b0

  rfemulator3:
    hostname: x0c0r2b0
    image: ghcr.io/openchami/csm-rie:v1.6.7
    environment:
      - MOCKUPFOLDER=Slingshot_Switch_Blade
      - XNAME=x0c0r2b0
      # - "AUTH_CONFIG=root:root_password:Administrator"
      - PORT=443
    ports:
      - "5003:443"
    networks:
      pcs:
        aliases:
          - x0c0r2b0
