name: run ct tests
on:
  - push
  - pull_request
  - workflow_dispatch
env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
jobs:
  run_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4
      - name: install docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: run ct tests
        run: docker compose -f docker-compose.test.ct.yaml up --build
